<?php

function clock_angle_menu() {
  $items['clock_angle'] = array(
    'title' = 'Clock Angle',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clock_angle_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function clock_angle_form() {
  $form['hour_input'] = array(
    '#title' => 'Hour',
    '#type' => 'textfield',
    '#description' => t('Please enter the hour:'),
  );
  $form['minute_input'] = array(
    '#title' => 'Minutes',
    '#type' => 'textfield',
    '#description' => t('Please enter the minutes:'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Enter',
  );
  return $form;
}
